2018-10-16 16:21:19 ERROR  : Error connecting to the server: fe_sendauth: no password supplied

2018-10-16 16:27:24 ERROR  : Error connecting to the server: SSL SYSCALL error: Connection reset by peer (0x00002746/10054)
expected authentication request from server, but received S

2018-10-16 16:27:44 ERROR  : Error connecting to the server: definition of service "postgres" not found

2018-10-19 16:40:44 ERROR  : Error connecting to the server: FATAL:  password authentication failed for user "chatbotdb"
FATAL:  password authentication failed for user "chatbotdb"

2018-10-19 16:40:58 ERROR  : Error connecting to the server: FATAL:  password authentication failed for user "chatbotdb"
FATAL:  password authentication failed for user "chatbotdb"

2018-10-19 16:41:38 ERROR  : Error connecting to the server: FATAL:  password authentication failed for user "chatbotdb"
FATAL:  password authentication failed for user "chatbotdb"

2018-10-19 16:41:51 ERROR  : Error connecting to the server: FATAL:  password authentication failed for user "root"
FATAL:  password authentication failed for user "root"

2018-10-19 16:42:41 ERROR  : Error connecting to the server: FATAL:  password authentication failed for user "chatbotdb"
FATAL:  password authentication failed for user "chatbotdb"

2018-10-19 21:56:56 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-10-19 21:57:07 ERROR  : Column not found in pgSet: usecreatedb
2018-10-19 21:57:10 ERROR  : Column not found in pgSet: usesuper
2018-10-19 21:57:11 ERROR  : Column not found in pgSet: upsince
2018-10-19 21:57:12 ERROR  : Column not found in pgSet: confloadedsince
2018-10-19 21:57:13 ERROR  : Column not found in pgSet: inrecovery
2018-10-19 21:57:14 ERROR  : Column not found in pgSet: replayloc
2018-10-19 21:57:14 ERROR  : Column not found in pgSet: receiveloc
2018-10-19 21:57:15 ERROR  : Column not found in pgSet: replay_timestamp
2018-10-19 21:57:16 ERROR  : Column not found in pgSet: isreplaypaused
2018-10-19 21:58:42 ERROR  : ERROR:  syntax error at or near "{"
LINE 1: CREATE TABLE bob {
                         ^
2018-10-19 22:01:44 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-10-19 22:01:50 ERROR  : Column not found in pgSet: usecreatedb
2018-10-19 22:01:54 ERROR  : Column not found in pgSet: usesuper
2018-10-19 22:01:55 ERROR  : Column not found in pgSet: upsince
2018-10-19 22:01:55 ERROR  : Column not found in pgSet: confloadedsince
2018-10-19 22:01:56 ERROR  : Column not found in pgSet: inrecovery
2018-10-19 22:01:56 ERROR  : Column not found in pgSet: replayloc
2018-10-19 22:01:57 ERROR  : Column not found in pgSet: receiveloc
2018-10-19 22:01:57 ERROR  : Column not found in pgSet: replay_timestamp
2018-10-19 22:01:58 ERROR  : Column not found in pgSet: isreplaypaused
2018-10-20 12:55:28 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-10-20 12:55:29 ERROR  : Column not found in pgSet: usecreatedb
2018-10-20 12:55:30 ERROR  : Column not found in pgSet: usesuper
2018-10-20 12:55:30 ERROR  : Column not found in pgSet: upsince
2018-10-20 12:55:30 ERROR  : Column not found in pgSet: confloadedsince
2018-10-20 12:55:31 ERROR  : Column not found in pgSet: inrecovery
2018-10-20 12:55:31 ERROR  : Column not found in pgSet: replayloc
2018-10-20 12:55:32 ERROR  : Column not found in pgSet: receiveloc
2018-10-20 12:55:32 ERROR  : Column not found in pgSet: replay_timestamp
2018-10-20 12:55:33 ERROR  : Column not found in pgSet: isreplaypaused
2018-10-30 12:22:51 ERROR  : ERROR:  function pg_last_xlog_receive_location() does not exist
LINE 1: ...E NULL END as inrecovery, CASE WHEN usesuper THEN pg_last_xl...
                                                             ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
2018-10-30 12:22:51 ERROR  : Column not found in pgSet: usecreatedb
2018-10-30 12:22:51 ERROR  : Column not found in pgSet: usesuper
2018-10-30 12:22:52 ERROR  : Column not found in pgSet: upsince
2018-10-30 12:22:52 ERROR  : Column not found in pgSet: confloadedsince
2018-10-30 12:22:52 ERROR  : Column not found in pgSet: inrecovery
2018-10-30 12:22:53 ERROR  : Column not found in pgSet: replayloc
2018-10-30 12:22:53 ERROR  : Column not found in pgSet: receiveloc
2018-10-30 12:22:53 ERROR  : Column not found in pgSet: replay_timestamp
2018-10-30 12:22:53 ERROR  : Column not found in pgSet: isreplaypaused
